# Generated by Django 3.2.3 on 2021-07-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=120)),
            ],
        ),
    ]
