# Generated by Django 3.2.3 on 2021-11-09 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empm', '0008_auto_20211029_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='company',
            new_name='companyId',
        ),
    ]
