# Generated by Django 3.2.10 on 2021-12-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empm', '0011_comment_monthlyoutput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyoutput',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyoutput',
            name='sick_hours',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='monthlyoutput',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyoutput',
            name='vacation_hours',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='monthlyoutput',
            name='working_hours',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
