# Generated by Django 3.2.10 on 2021-12-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empm', '0013_overallmonthlyoutput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overallmonthlyoutput',
            name='sick_hours',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='overallmonthlyoutput',
            name='vacation_hours',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='overallmonthlyoutput',
            name='working_hours',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
    ]
