# Generated by Django 3.2.3 on 2021-07-26 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empm', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empm.company'),
        ),
        migrations.AddField(
            model_name='employee',
            name='health_limitations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_assign_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='med_exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='working_category',
            field=models.CharField(default='A', max_length=1),
            preserve_default=False,
        ),
    ]
