# Generated by Django 3.2.3 on 2021-07-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empm', '0004_alter_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.PositiveIntegerField(default=123456789),
            preserve_default=False,
        ),
    ]
