# Generated by Django 3.2.3 on 2021-12-21 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empm', '0010_auto_20211109_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_hours', models.DecimalField(decimal_places=1, max_digits=3)),
                ('sick_hours', models.DecimalField(decimal_places=1, max_digits=3)),
                ('vacation_hours', models.DecimalField(decimal_places=1, max_digits=3)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empm.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateField()),
                ('monthly_output', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empm.monthlyoutput')),
            ],
        ),
    ]
