# Generated by Django 3.2.3 on 2022-01-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empm', '0014_auto_20211227_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
