# Generated by Django 3.2.3 on 2022-01-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empm', '0015_auto_20220116_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
