# Generated by Django 3.2.3 on 2022-04-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empm', '0016_auto_20220120_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='company_profile_photos/'),
        ),
    ]
