name: Node.js CI

on:
  push:
    branches:
    - main
    - feat/*
    - fix/*
    - test/*

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
        cache-dependency-path: frontend2/package-lock.json

    - name: Install dependencies
      working-directory: ./frontend2
      run: npm install

    - name: Run the tests
      working-directory: ./frontend2
      run: npm run test

    - name: Build
      working-directory: ./frontend2
      run: npm run build
