name: Node.js CI

on:
  push:
    branches:
    - main
    - feat/*
    - fix/*
    - test/*

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

#    - name: Set up Node.js ${{ matrix.node-version }}
#      uses: actions/setup-node@v2
#      with:
#        node-version: ${{ matrix.node-version }}
#        cache: npm
#        cache-dependency-path: frontend2/package-lock.json

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

    - name: Install Python dependecies from Pipfile
      working-directory: ./empmanager
      run: pipenv install --system

   - name: Install Python dependecies from Pipfile
     working-directory: ./empmanager
     run: python3 manage.py testserver test-data


#    - name: Install dependencies
#      working-directory: ./frontend2
#      run: npm install --legacy-peer-deps
#
#    - name: Run the tests
#      working-directory: ./frontend2
#      run: npm run test
#
#    - name: Build
#      working-directory: ./frontend2
#      run: npm run build
