name: Node.js CI

on:
  push:
    branches:
    - main
    - feat/*
    - fix/*
    - test/*

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
        cache-dependency-path: frontend/package-lock.json

    - name: Install Node.js dependencies
      working-directory: ./frontend
      run: npm install --legacy-peer-deps

    - name: Run the unit tests
      working-directory: ./frontend
      run: npm run test

    - name: Build
      working-directory: ./frontend
      run: npm run build

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Install pipenv
      run: pip install pipenv

    - name: Install Swagger
      run: pip install drf-yasg

    - name: Install DCH
      run: pip install django-cors-headers

    - name: Install Python dependecies from Pipfile
      working-directory: ./api
      run: pipenv install --system

    - name: Start Django server with test DB, frontend and run E2E tests
      working-directory: ./api
      run: | 
            python3 manage.py testserver test-data &
            cd ../frontend
            npm run ci
